name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  Artillery:
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: CheckoÍut repository
        uses: actions/checkout@v3

      - name: Execute load test
        run: /home/node/artillery/bin/run run -q --environment functional ./load-test.yml
      - name: Execute Second load tests
        run: /home/node/artillery/bin/run run -q --environment functional ./second-load-test.yml
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is the cleanup Job"