name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  Artillery:
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute load tests
        run: /home/node/artillery/bin/run run -q --environment functional ./load-test.yml