name: GitHub Actions Demo
on:
  push:
    branches:
      - master
jobs:
  Wait-For-Ready:
    runs-on: ubuntu-latest
    steps:
      - name: Wait-For-Ready_200-OK
        uses: nev7n/wait_for_response@v1
        with:
          url: 'https://shrouded-eyrie-09530.herokuapp.com/_health'
          responseCode: 200
          timeout: 20000
          interval: 1000
  Seeding:
    needs: Wait-For-Ready
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is the seeding Job"
  Artillery:
    needs: Seeding
    runs-on: ubuntu-latest
    container: artilleryio/artillery:latest
    steps:
      - name: CheckoÍut repository
        uses: actions/checkout@v3
      - name: Execute load test
        run: /home/node/artillery/bin/run run -q --environment functional ./load-test.yml
      - name: Execute Second load tests
        run: /home/node/artillery/bin/run run -q --environment functional ./second-load-test.yml
  Cleanup:
    if: ${{ always() }}
    needs: [Seeding, Artillery, Wait-For-ready]
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is the cleanup Job"